### ISSUE TITLE
Double sentence in requirements page, constraint is mentioned twice, also in non-functional

### ISSUE THREAD

**Issue by Peter-Buenk** [Iasa-Global/btabok#73]
Types of Requirements
Requirements are typically placed into these categories:

Functional requirement ─ Describe the functionality that the system is to execute; for example, formatting some text or modulating a signal. They are sometimes known as features.
Non-functional requirements ─ **Are the ones that act to constrain the solution**. Nonfunctional requirements are known as quality attribute requirements.
Constraint requirements ─ Are the ones that act to constrain the solution. No matter how the problem is solved the constraint requirements must be adhered to

**Comment by paultpreiss** [comment]
Fixed and committed.
